apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: 
  namespace: 
spec:
  selector:
    matchLabels:
      app: 
  replicas:  # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: 
        image: 
        ports:
        - containerPort:
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        
---
kind: Service
apiVersion: v1
metadata:
  name: aks
  namespace: bcxnamespace
spec:
  selector:
    app: aks
  ports:
  - protocol: TCP
    port: 
    targetPort: 
  type: LoadBalancer